version: "3.3"
services:
  postgres:
    image: postgres:11.21-bullseye
    ports: 
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}